import { useState } from 'react';
import { Heart, Plus, UserCircle } from 'lucide-react';
import CharacterCreator from '../components/CharacterCreator';
import HeroSheet from '../components/HeroSheet';

export default function HeroesScreen({ heroes, editingHero, setEditingHero, createHero, updateHero, deleteHero, toggleHeroSkill, toggleDisabledSkill }) {
 const [creating,setCreating]=useState(false);
 if(creating)return <CharacterCreator onCancel={()=>setCreating(false)} onComplete={details=>{const hero=createHero({...details,baseMaxStamina:details.maxStamina});setCreating(false);setEditingHero(hero.id);}}/>;
 if(editingHero){const hero=heroes.find(item=>item.id===editingHero);if(!hero)return null;return <HeroSheet hero={hero} partySize={heroes.length} onBack={()=>setEditingHero(null)} updateHero={updateHero} deleteHero={id=>{deleteHero(id);setEditingHero(null);}} toggleHeroSkill={toggleHeroSkill} toggleDisabledSkill={toggleDisabledSkill}/>;}
 const bonus=heroes.length===1?4:heroes.length===2?2:0;
 return <div className="space-y-5 animate-in fade-in duration-300"><div className="flex items-end justify-between gap-4"><div><div className="ink-label text-[9px] text-[#8a7767]">The company</div><h2 className="display-serif text-3xl font-bold text-[#3e3028]">Hero Roster</h2></div><button onClick={()=>setCreating(true)} className="px-3.5 py-2.5 bg-[#762b2b] hover:bg-[#642323] text-white rounded-xl font-bold flex items-center gap-2 shadow"><Plus size={18}/><span className="hidden sm:inline">Create Hero</span></button></div><div className="h-px bg-gradient-to-r from-transparent via-[#b79f78] to-transparent"/>
 {heroes.length===0&&<div className="paper-panel text-center rounded-2xl py-14 text-[#8a7767]"><UserCircle size={46} className="mx-auto mb-3 opacity-40"/><p className="display-serif text-xl font-bold text-[#5c4a3d]">The roster is empty</p><p className="text-sm mt-1">Create a hero to begin your company.</p></div>}
 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{heroes.map(hero=>{const baseMax=hero.baseMaxStamina??hero.maxStamina??14;const effectiveMax=baseMax+bonus;const current=Math.min(hero.currentStamina??effectiveMax,effectiveMax);return <button key={hero.id} onClick={()=>setEditingHero(hero.id)} className="paper-panel group text-left p-5 rounded-2xl hover:border-[#a47d65] transition-all"><div className="flex justify-between items-start gap-4"><div><div className="ink-label text-[8px] text-[#8b4b42]">Hero of Terrinoth</div><h3 className="display-serif font-bold text-[#3e3028] text-2xl leading-tight mt-1">{hero.name}</h3><p className="ink-label text-[8px] text-[#8a7767] mt-2">{hero.race} · {hero.class}</p></div><div className="shrink-0 rounded-xl border border-[#d2c2a5] bg-[#fffaf0]/70 px-3 py-2 text-center"><Heart size={14} className="mx-auto text-[#7b2d2d]"/><div className="display-serif font-bold text-xl text-[#7b2d2d] leading-none mt-1">{current}/{effectiveMax}</div><div className="ink-label text-[7px] text-[#8a7767] mt-1">Stamina</div></div></div><div className="my-4 h-px bg-[#d8c9aa]"/><div className="text-sm text-[#5c4a3d]"><strong>{hero.skills.length} skills</strong><span className="text-[#a18e7d]"> · </span>{hero.skills.slice(0,4).join(', ')}{hero.skills.length>4?'…':''}</div>{hero.personality&&<p className="mt-3 text-sm italic leading-relaxed text-[#75665b] line-clamp-2">“{hero.personality}”</p>}{bonus>0&&<div className="ink-label text-[7px] text-[#9a8068] mt-4">+{bonus} party stamina bonus</div>}</button>})}</div></div>;
}
