import { Award, Coins, Feather, Minus, Plus, ScrollText } from 'lucide-react';
import StoryPointGrid from '../components/StoryPointGrid';

export default function PartyScreen({ party, setParty, onToggleStoryPoint }) {
 const adjust=(key,delta)=>setParty(current=>({...current,[key]:Math.max(0,current[key]+delta)}));
 return <div className="space-y-6 animate-in fade-in duration-300">
  <header><div className="ink-label text-[9px] text-[#8a7767]">Campaign ledger</div><h2 className="display-serif text-3xl font-bold text-[#3e3028]">Story & Party</h2><p className="text-sm text-[#78675a] mt-1">The shared record carried by the whole company.</p></header><div className="h-px bg-gradient-to-r from-transparent via-[#b79f78] to-transparent"/>
  <section className="grid sm:grid-cols-2 gap-3"><Resource icon={Award} label="Fame" value={party.fame} minus={()=>adjust('fame',-1)} plus={()=>adjust('fame',1)}/><Resource icon={Coins} label="Gold" value={party.gold} minus={()=>adjust('gold',-5)} plus={()=>adjust('gold',5)} editable onChange={value=>setParty(current=>({...current,gold:value}))}/></section>
  <section className="paper-panel rounded-2xl p-5 sm:p-6"><div className="flex items-end justify-between gap-3 mb-4"><div><div className="ink-label text-[9px] text-[#8a7767]">Campaign marks</div><h3 className="display-serif text-2xl font-bold text-[#453329]">Story Points</h3></div><div className="display-serif text-2xl font-bold text-[#7b2d2d]">{party.storyPoints.length}</div></div><p className="text-sm text-[#78675a] mb-5">Mark the story points your party has recorded during play.</p><StoryPointGrid storyPoints={party.storyPoints} onToggle={onToggleStoryPoint}/></section>
  <section className="paper-panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3 mb-4"><div className="w-9 h-9 rounded-full bg-[#efe3c8] flex items-center justify-center"><Feather size={17} className="text-[#7b2d2d]"/></div><div><div className="ink-label text-[9px] text-[#8a7767]">Loose pages</div><h3 className="display-serif text-xl font-bold text-[#453329]">Campaign Notes</h3></div></div><textarea value={party.notes} onChange={event=>setParty(current=>({...current,notes:event.target.value}))} className="w-full min-h-40 p-4 bg-[#fffdf5]/65 border border-[#d2c2a5] rounded-xl focus:outline-none focus:border-[#8c5a50] leading-relaxed" placeholder="Jot down hints, locations, clues, names, and anything the party wants to remember…"/></section>
 </div>;
}
function Resource({icon:Icon,label,value,minus,plus,editable,onChange}){return <div className="paper-panel rounded-2xl p-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-[#efe3c8] border border-[#d0bd96] flex items-center justify-center"><Icon size={18} className="text-[#7b2d2d]"/></div><div><div className="ink-label text-[8px] text-[#8a7767]">Party resource</div><div className="display-serif text-xl font-bold text-[#453329]">{label}</div></div></div><div className="flex items-center gap-2"><button aria-label={`Decrease ${label}`} onClick={minus} className="p-2 rounded-full bg-[#e9dfc8] text-[#5c4a3d]"><Minus size={15}/></button>{editable?<input type="number" value={value} onChange={e=>onChange(Number.parseInt(e.target.value,10)||0)} className="display-serif w-16 text-center bg-transparent text-xl font-bold text-[#7b2d2d] border-b border-[#c7b590] outline-none"/>:<span className="display-serif text-2xl font-bold text-[#7b2d2d] min-w-8 text-center">{value}</span>}<button aria-label={`Increase ${label}`} onClick={plus} className="p-2 rounded-full bg-[#e9dfc8] text-[#5c4a3d]"><Plus size={15}/></button></div></div>}
