import { useState } from 'react';
import { Award, BookOpen, Check, Clock, Coins, Heart, Map, Pencil, Plus, ScrollText, Users } from 'lucide-react';
import { DAY_SLOTS } from '../data/gameData';

function Stat({icon:Icon,label,value}){return <div className="flex items-center gap-3 rounded-lg border border-[#d2c2a5] bg-white/60 px-3 py-3"><Icon size={19} className="text-[#8c2a2a]"/><div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8c8c8c]">{label}</div><div className="text-lg font-bold text-[#4a3b32]">{value}</div></div></div>}
export default function SessionScreen({party,heroes,adventure,village,onAdvanceTime,onOpenParty,onOpenHeroes,onOpenVillage,onUpdateAdventure,onStartAdventure,onCompleteAdventure}){
 const [starting,setStarting]=useState(false); const maxTime=DAY_SLOTS[village.day]||8; const hasAdventure=Boolean(adventure.title?.trim());
 const submitStart=e=>{e.preventDefault();const data=new FormData(e.currentTarget);onStartAdventure({title:data.get('title'),location:data.get('location'),inVillage:data.get('inVillage')==='on'});setStarting(false);};
 return <div className="space-y-5 animate-in fade-in duration-300">
  <section className="overflow-hidden rounded-xl border border-[#c2b29a] bg-[#f8f4e6] shadow-md"><div className="bg-[#4a3b32] px-5 py-5 text-[#f8f4e6] sm:px-6"><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#d2c2a5]"><ScrollText size={15}/> Current adventure</div>{hasAdventure?<><input value={adventure.title} onChange={e=>onUpdateAdventure({title:e.target.value})} className="w-full bg-transparent text-2xl font-bold sm:text-3xl outline-none border-b border-transparent focus:border-[#d2c2a5]"/><div className="mt-2 flex items-center gap-2 text-[#e8e0cc]"><Map size={16}/><input value={adventure.location||''} onChange={e=>onUpdateAdventure({location:e.target.value})} placeholder="Current location" className="w-full bg-transparent outline-none placeholder:text-[#bcae9c]"/></div></>:<h2 className="text-2xl font-bold">Between adventures</h2>}</div>
  {hasAdventure?<div className="p-5 sm:p-6 space-y-4"><label className="block"><span className="text-xs uppercase tracking-wider font-bold text-[#75665b]">Section / reference</span><input value={adventure.section||''} onChange={e=>onUpdateAdventure({section:e.target.value})} placeholder="Optional section number or your own reference" className="mt-1 w-full bg-white border border-[#d2c2a5] rounded-lg px-3 py-2.5 outline-none focus:border-[#8c2a2a]"/></label><label className="block"><span className="text-xs uppercase tracking-wider font-bold text-[#75665b]">Adventure notes</span><textarea value={adventure.notes||''} onChange={e=>onUpdateAdventure({notes:e.target.value})} placeholder="Record only what you want to remember…" className="mt-1 w-full min-h-24 bg-white border border-[#d2c2a5] rounded-lg p-3 outline-none focus:border-[#8c2a2a]"/></label><div className="flex items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm font-bold text-[#5c4a3d]"><input type="checkbox" checked={adventure.inVillage} onChange={e=>onUpdateAdventure({inVillage:e.target.checked})}/> In Dragonholt Village</label><button onClick={onCompleteAdventure} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-[#b8a688] bg-white text-sm font-bold text-[#5c4a3d]"><Check size={16}/> Complete</button></div></div>:<div className="p-5"><button onClick={()=>setStarting(true)} className="w-full flex items-center justify-center gap-2 rounded-lg bg-[#8c2a2a] text-white py-3 font-bold"><Plus size={18}/> Begin an Adventure</button></div>}</section>
  {starting&&<form onSubmit={submitStart} className="rounded-xl border-2 border-[#8c2a2a] bg-[#f8f4e6] p-5 shadow"><h3 className="font-bold text-xl text-[#3e3028]">Begin an adventure</h3><p className="text-sm text-[#75665b] mt-1 mb-4">Give the session enough context to find your place again later.</p><div className="space-y-3"><input name="title" required placeholder="Adventure or quest name" className="w-full bg-white border border-[#d2c2a5] rounded-lg px-3 py-2.5"/><input name="location" placeholder="Starting location" className="w-full bg-white border border-[#d2c2a5] rounded-lg px-3 py-2.5"/><label className="flex items-center gap-2 text-sm"><input name="inVillage" type="checkbox"/> Starting in Dragonholt Village</label><div className="flex gap-2"><button type="submit" className="px-4 py-2 bg-[#8c2a2a] text-white rounded-lg font-bold">Start</button><button type="button" onClick={()=>setStarting(false)} className="px-4 py-2 bg-[#e8e0cc] rounded-lg font-bold">Cancel</button></div></div></form>}
  {adventure.inVillage&&<section className="rounded-xl border border-[#d2c2a5] bg-[#f8f4e6] p-5 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-[#8c8c8c]">Dragonholt Village</div><h3 className="font-bold text-[#4a3b32]">Day {village.day} · {village.time}/{maxTime} time</h3></div><button onClick={onOpenVillage} className="text-sm font-bold text-[#8c2a2a]">Village tracker</button></div><div className="flex gap-1.5 mt-3">{Array.from({length:maxTime}).map((_,i)=><div key={i} className={`h-2 flex-1 rounded-full ${i<village.time?'bg-[#8c2a2a]':'bg-[#d8cdb8]'}`}/>)}</div><button onClick={onAdvanceTime} disabled={village.time>=maxTime} className="mt-3 w-full flex items-center justify-center gap-2 rounded-lg bg-[#8c2a2a] text-white py-2.5 font-bold disabled:opacity-40"><Clock size={17}/> Advance Village Time</button></section>}
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={Award} label="Fame" value={party.fame}/><Stat icon={Coins} label="Gold" value={party.gold}/><Stat icon={BookOpen} label="Story points" value={party.storyPoints.length}/><Stat icon={Users} label="Heroes" value={heroes.length}/></section>
  <section className="rounded-xl border border-[#d2c2a5] bg-[#f8f4e6] p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="text-xl font-bold text-[#4a3b32]">Your heroes</h3><button onClick={onOpenHeroes} className="text-sm font-bold text-[#8c2a2a]">View all</button></div>{heroes.length===0?<button onClick={onOpenHeroes} className="w-full border border-dashed border-[#c2b29a] rounded-lg py-5 font-bold text-[#6b5849]">+ Add your first hero</button>:<div className="grid gap-2 sm:grid-cols-2">{heroes.map(hero=>{const bonus=heroes.length===1?4:heroes.length===2?2:0;const max=(hero.baseMaxStamina??hero.maxStamina??0)+bonus;return <button key={hero.id} onClick={onOpenHeroes} className="flex items-center justify-between rounded-lg border border-[#ded2bd] bg-white/60 p-3 text-left"><div><div className="font-bold text-[#4a3b32]">{hero.name}</div><div className="text-xs text-[#8c8c8c]">{hero.race} · {hero.class}</div></div><div className="flex items-center gap-1.5 font-bold text-[#8c2a2a]"><Heart size={16}/>{Math.min(hero.currentStamina??max,max)}/{max}</div></button>})}</div>}</section>
  {adventure.history?.length>0&&<section className="rounded-xl border border-[#d2c2a5] bg-[#f8f4e6] p-5 shadow-sm"><h3 className="font-bold text-[#4a3b32] flex items-center gap-2"><BookOpen size={18}/> Adventure Journal</h3><div className="mt-3 space-y-3">{adventure.history.map(entry=><details key={entry.id} className="border-t border-[#d8cdb8] pt-3"><summary className="cursor-pointer font-bold text-[#5c4a3d]">{entry.title}<span className="ml-2 font-normal text-xs text-[#8c8c8c]">{entry.location}</span></summary>{entry.section&&<p className="text-xs text-[#8c2a2a] mt-2">Last reference: {entry.section}</p>}{entry.notes&&<p className="text-sm whitespace-pre-wrap text-[#75665b] mt-2">{entry.notes}</p>}</details>)}</div></section>}
  <button onClick={onOpenParty} className="w-full rounded-xl border border-[#d2c2a5] bg-[#f8f4e6] p-4 text-left shadow-sm"><div className="flex items-center gap-2 font-bold text-[#4a3b32]"><Pencil size={18} className="text-[#8c2a2a]"/> Story, Party & Campaign Notes</div></button>
 </div>;
}
