import { useState } from 'react';
import { Award, BookOpen, Check, Clock, Coins, Feather, Heart, MapPin, Plus, ScrollText, Users } from 'lucide-react';
import { DAY_SLOTS } from '../data/gameData';

function Stat({icon:Icon,label,value}){return <div className="paper-panel rounded-xl px-3 py-3.5 flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-[#efe3c8] border border-[#d0bd96] flex items-center justify-center"><Icon size={17} className="text-[#7b2d2d]"/></div><div><div className="ink-label text-[8px] text-[#8a7767]">{label}</div><div className="display-serif text-xl font-bold text-[#3c2c23] leading-none mt-1">{value}</div></div></div>}
export default function SessionScreen({party,heroes,adventure,village,onAdvanceTime,onOpenParty,onOpenHeroes,onOpenVillage,onUpdateAdventure,onStartAdventure,onCompleteAdventure}){
 const [starting,setStarting]=useState(false); const maxTime=DAY_SLOTS[village.day]||8; const hasAdventure=Boolean(adventure.title?.trim()); const submitStart=e=>{e.preventDefault();const data=new FormData(e.currentTarget);onStartAdventure({title:data.get('title'),location:data.get('location'),inVillage:data.get('inVillage')==='on'});setStarting(false);};
 return <div className="space-y-5 animate-in fade-in duration-300">
  <section className="paper-panel overflow-hidden rounded-2xl"><div className="relative overflow-hidden bg-[#47332a] px-5 py-6 sm:px-7 text-[#fff7e5]"><div className="absolute -right-8 -top-12 w-48 h-48 rounded-full border border-[#80664d] opacity-40"/><div className="absolute -right-2 -top-5 w-28 h-28 rounded-full border border-[#80664d] opacity-30"/><div className="relative"><div className="ink-label mb-2 flex items-center gap-2 text-[9px] text-[#d7c09a]"><ScrollText size={14}/> Current adventure</div>{hasAdventure?<><input value={adventure.title} onChange={e=>onUpdateAdventure({title:e.target.value})} className="display-serif w-full bg-transparent text-3xl sm:text-4xl font-bold outline-none border-b border-transparent focus:border-[#a98b68] placeholder:text-[#a99377]"/><div className="mt-3 flex items-center gap-2 text-[#e3d4bc]"><MapPin size={15}/><input value={adventure.location||''} onChange={e=>onUpdateAdventure({location:e.target.value})} placeholder="Current location" className="w-full bg-transparent text-sm outline-none placeholder:text-[#a99377]"/></div></>:<><h2 className="display-serif text-3xl font-bold">Between adventures</h2><p className="mt-2 text-sm text-[#d8c8b0]">Your journal is ready for the next chapter.</p></>}</div></div>
  {hasAdventure?<div className="p-5 sm:p-7 space-y-5"><label className="block"><span className="ink-label text-[9px] text-[#806e5e]">Section / reference</span><input value={adventure.section||''} onChange={e=>onUpdateAdventure({section:e.target.value})} placeholder="Optional section number or your own reference" className="mt-1.5 w-full bg-transparent border-0 border-b border-[#c9b895] px-0 py-2 outline-none focus:border-[#7b2d2d]"/></label><label className="block"><span className="ink-label text-[9px] text-[#806e5e]">Field notes</span><textarea value={adventure.notes||''} onChange={e=>onUpdateAdventure({notes:e.target.value})} placeholder="Record what you want to remember…" className="mt-2 w-full min-h-24 bg-[#fffdf5]/60 border border-[#d2c2a5] rounded-xl p-3.5 outline-none focus:border-[#8c5a50] leading-relaxed"/></label><div className="flex items-center justify-between gap-3 border-t border-[#d8c9aa] pt-4"><label className="flex items-center gap-2 text-sm font-bold text-[#5c4a3d]"><input type="checkbox" checked={adventure.inVillage} onChange={e=>onUpdateAdventure({inVillage:e.target.checked})} className="accent-[#7b2d2d]"/> In Dragonholt Village</label><button onClick={onCompleteAdventure} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-[#b8a688] bg-[#fffaf0] text-sm font-bold text-[#5c4a3d]"><Check size={16}/> Complete</button></div></div>:<div className="p-5 sm:p-7"><button onClick={()=>setStarting(true)} className="w-full flex items-center justify-center gap-2 rounded-xl bg-[#762b2b] text-white py-3 font-bold shadow hover:bg-[#642323]"><Plus size={18}/> Begin an Adventure</button></div>}</section>
  {starting&&<form onSubmit={submitStart} className="paper-panel rounded-2xl p-5 sm:p-6 border-2 border-[#8b4b42]"><div className="rule-flourish ink-label text-[9px] text-[#8b4b42] mb-3">New chapter</div><h3 className="display-serif font-bold text-2xl text-[#3e3028]">Begin an adventure</h3><p className="text-sm text-[#75665b] mt-1 mb-5">Give the session enough context to find your place again later.</p><div className="space-y-3"><input name="title" required placeholder="Adventure or quest name" className="w-full bg-[#fffdf5] border border-[#d2c2a5] rounded-lg px-3 py-2.5"/><input name="location" placeholder="Starting location" className="w-full bg-[#fffdf5] border border-[#d2c2a5] rounded-lg px-3 py-2.5"/><label className="flex items-center gap-2 text-sm"><input name="inVillage" type="checkbox" className="accent-[#7b2d2d]"/> Starting in Dragonholt Village</label><div className="flex gap-2 pt-2"><button type="submit" className="px-4 py-2 bg-[#762b2b] text-white rounded-lg font-bold">Start</button><button type="button" onClick={()=>setStarting(false)} className="px-4 py-2 bg-[#e8dfca] rounded-lg font-bold">Cancel</button></div></div></form>}
  {adventure.inVillage&&<section className="paper-panel rounded-2xl p-5"><div className="flex items-center justify-between"><div><div className="ink-label text-[9px] text-[#8a7767]">Dragonholt Village</div><h3 className="display-serif text-xl font-bold text-[#453329] mt-1">Day {village.day} <span className="font-normal text-[#8a7767]">· {village.time}/{maxTime}</span></h3></div><button onClick={onOpenVillage} className="text-xs font-bold text-[#7b2d2d] border-b border-[#b98e7e]">Open tracker</button></div><div className="flex gap-1.5 mt-4">{Array.from({length:maxTime}).map((_,i)=><div key={i} className={`h-2 flex-1 rounded-full border ${i<village.time?'bg-[#7b2d2d] border-[#682323]':'bg-[#e5dbc4] border-[#d0c09f]'}`}/>)}</div><button onClick={onAdvanceTime} disabled={village.time>=maxTime} className="mt-4 w-full flex items-center justify-center gap-2 rounded-lg border border-[#b99f77] bg-[#efe4cb] text-[#5a4032] py-2.5 font-bold disabled:opacity-40"><Clock size={17}/> Advance Village Time</button></section>}
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={Award} label="Fame" value={party.fame}/><Stat icon={Coins} label="Gold" value={party.gold}/><Stat icon={BookOpen} label="Story points" value={party.storyPoints.length}/><Stat icon={Users} label="Heroes" value={heroes.length}/></section>
  <section className="paper-panel rounded-2xl p-5 sm:p-6"><div className="mb-4 flex items-end justify-between"><div><div className="ink-label text-[9px] text-[#8a7767]">The company</div><h3 className="display-serif text-2xl font-bold text-[#453329]">Your heroes</h3></div><button onClick={onOpenHeroes} className="text-xs font-bold text-[#7b2d2d]">View roster →</button></div>{heroes.length===0?<button onClick={onOpenHeroes} className="w-full border border-dashed border-[#bca884] rounded-xl py-5 font-bold text-[#6b5849]">+ Add your first hero</button>:<div className="grid gap-2 sm:grid-cols-2">{heroes.map(hero=>{const bonus=heroes.length===1?4:heroes.length===2?2:0;const max=(hero.baseMaxStamina??hero.maxStamina??0)+bonus;return <button key={hero.id} onClick={onOpenHeroes} className="group flex items-center justify-between rounded-xl border border-[#d2c2a5] bg-[#fffdf5]/65 p-3.5 text-left hover:border-[#aa8973]"><div><div className="display-serif font-bold text-lg text-[#453329]">{hero.name}</div><div className="ink-label text-[8px] text-[#8a7767] mt-1">{hero.race} · {hero.class}</div></div><div className="flex items-center gap-1.5 font-bold text-[#7b2d2d]"><Heart size={15}/>{Math.min(hero.currentStamina??max,max)}/{max}</div></button>})}</div>}</section>
  {adventure.history?.length>0&&<section className="paper-panel rounded-2xl p-5 sm:p-6"><div className="rule-flourish ink-label text-[9px] text-[#8a7767]">Past chapters</div><h3 className="display-serif text-2xl text-center font-bold text-[#453329] mt-2">Adventure Journal</h3><div className="mt-4 space-y-1">{adventure.history.map(entry=><details key={entry.id} className="border-t border-[#d8cdb8] py-3"><summary className="cursor-pointer display-serif font-bold text-lg text-[#5c4033]">{entry.title}<span className="ml-2 font-normal text-xs text-[#8c8c8c]">{entry.location}</span></summary>{entry.section&&<p className="ink-label text-[8px] text-[#8c2a2a] mt-2">Last reference · {entry.section}</p>}{entry.notes&&<p className="text-sm whitespace-pre-wrap text-[#75665b] mt-2 leading-relaxed">{entry.notes}</p>}</details>)}</div></section>}
  <button onClick={onOpenParty} className="paper-panel w-full rounded-2xl p-4 text-left"><div className="flex items-center gap-3 font-bold text-[#4a3b32]"><div className="w-9 h-9 rounded-full bg-[#efe3c8] flex items-center justify-center"><Feather size={17} className="text-[#7b2d2d]"/></div><div><div className="display-serif text-lg">Story, Party & Campaign Notes</div><div className="text-xs font-normal text-[#887565]">Story points, resources, and the wider campaign record.</div></div></div></button>
 </div>;
}
