import { useState } from 'react';
import { ChevronLeft, Edit3, Heart, Minus, Plus, Sparkles, Trash2, X } from 'lucide-react';
import { SKILLS } from '../data/gameData';
const partyBonus=count=>count===1?4:count===2?2:0;
export default function HeroSheet({hero,partySize,onBack,updateHero,deleteHero,toggleHeroSkill,toggleDisabledSkill}){
 const[editing,setEditing]=useState(false);const bonus=partyBonus(partySize);const baseMax=hero.baseMaxStamina??hero.maxStamina??14;const effectiveMax=baseMax+bonus;const current=Math.min(hero.currentStamina??effectiveMax,effectiveMax);const adjustStamina=delta=>updateHero(hero.id,{currentStamina:Math.max(0,Math.min(effectiveMax,current+delta))});const adjustExp=delta=>updateHero(hero.id,{exp:Math.max(0,(hero.exp||0)+delta)});
 return <div className="max-w-3xl mx-auto animate-in slide-in-from-right-4 duration-300"><div className="flex items-center justify-between mb-4"><button onClick={onBack} className="flex items-center gap-1 text-[#7b2d2d] font-bold"><ChevronLeft size={20}/> Roster</button><button onClick={()=>setEditing(!editing)} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-[#cbb99b] bg-[#f8f1df] text-[#5b4639] font-bold">{editing?<X size={16}/>:<Edit3 size={16}/>} {editing?'Done':'Edit'}</button></div>
 <article className="paper-panel rounded-2xl overflow-hidden"><header className="relative px-5 py-8 sm:px-8 text-center bg-[linear-gradient(145deg,#eee1c7,#f8efd9)] border-b border-[#cbb99b]"><div className="absolute inset-x-10 top-4 h-px bg-gradient-to-r from-transparent via-[#b69b70] to-transparent"/><div className="ink-label text-[9px] text-[#8b4b42] mb-2">Hero of Terrinoth</div>{editing?<input value={hero.name} onChange={e=>updateHero(hero.id,{name:e.target.value})} className="display-serif w-full text-center text-3xl sm:text-4xl font-bold bg-transparent border-b border-[#bda98a] text-[#3e3028] outline-none"/>:<h2 className="display-serif text-4xl sm:text-5xl font-bold text-[#3e3028] leading-tight">{hero.name}</h2>}<div className="ink-label mt-3 text-[9px] text-[#7b2d2d]">{hero.race} · {hero.class}</div>{(hero.age||hero.gender)&&<div className="mt-2 text-sm italic text-[#75665b]">{[hero.age&&`Age ${hero.age}`,hero.gender].filter(Boolean).join(' · ')}</div>}</header>
 <div className="p-4 sm:p-7 space-y-7"><div className="grid grid-cols-2 gap-3"><StatPanel icon={<Heart size={17}/>} label="Stamina" value={`${current} / ${effectiveMax}`} sub={bonus?`${baseMax} base · +${bonus} party`:`${baseMax} base`} onMinus={()=>adjustStamina(-1)} onPlus={()=>adjustStamina(1)}/><StatPanel icon={<Sparkles size={17}/>} label="Experience" value={hero.exp||0} sub="available XP" onMinus={()=>adjustExp(-1)} onPlus={()=>adjustExp(1)}/></div>
 <Section title={`Skills · ${hero.skills.length}`}><div className="grid grid-cols-2 sm:grid-cols-3 gap-2">{hero.skills.map(skill=>{const disabled=(hero.disabledSkills||[]).includes(skill);return <button key={skill} onClick={()=>toggleDisabledSkill(hero.id,skill)} className={`text-left px-3 py-2.5 rounded-lg border ${disabled?'border-[#c9aaa0] bg-[#f0e0da] text-[#98564d] line-through':'border-[#d7c8ad] bg-[#fffdf5]/75 text-[#49382f]'}`}><span className="font-bold text-sm">{skill}</span>{disabled&&<span className="ink-label block text-[7px] no-underline mt-1">Disabled</span>}</button>})}</div>{editing&&<SkillEditor hero={hero} toggleHeroSkill={toggleHeroSkill}/>}</Section>
 <NarrativeSection title="Physical Description" value={hero.physicalDescription} fallback="No physical description recorded." editing={editing} onChange={value=>updateHero(hero.id,{physicalDescription:value})}/><NarrativeSection title="Personality & Ideals" value={hero.personality} fallback="No personality or ideals recorded." editing={editing} onChange={value=>updateHero(hero.id,{personality:value})}/><NarrativeSection title="Background" value={hero.background} fallback="No background recorded." editing={editing} onChange={value=>updateHero(hero.id,{background:value})}/><Section title="Items & Potions">{editing?<textarea value={hero.items||''} onChange={e=>updateHero(hero.id,{items:e.target.value})} className="w-full min-h-28 p-3 bg-[#fffdf5] border border-[#d2c2a5] rounded-xl outline-none focus:border-[#8c5a50]" placeholder="Record carried items and potions…"/>:<p className={`text-sm whitespace-pre-wrap leading-relaxed ${hero.items?'text-[#4e4037]':'text-[#9a8d81] italic'}`}>{hero.items||'No items recorded.'}</p>}</Section>{editing&&<div className="pt-3 border-t border-[#d2c2a5]"><button onClick={()=>deleteHero(hero.id)} className="text-[#8a3434] flex items-center gap-2 text-sm font-bold"><Trash2 size={16}/> Delete this hero</button></div>}</div></article></div>;
}
function StatPanel({icon,label,value,sub,onMinus,onPlus}){return <div className="rounded-xl p-3 text-center border border-[#d2c2a5] bg-[#fffdf5]/70"><div className="flex justify-center items-center gap-1.5 text-[#7b2d2d]">{icon}<span className="ink-label text-[8px]">{label}</span></div><div className="flex items-center justify-center gap-2 mt-2"><button onClick={onMinus} className="p-1.5 rounded-full bg-[#e9dfc8] text-[#5c4a3d]"><Minus size={14}/></button><span className="display-serif text-2xl font-bold text-[#3e3028] min-w-16">{value}</span><button onClick={onPlus} className="p-1.5 rounded-full bg-[#e9dfc8] text-[#5c4a3d]"><Plus size={14}/></button></div><div className="text-[10px] text-[#8b7b6d] mt-1">{sub}</div></div>}
function Section({title,children}){return <section><div className="rule-flourish mb-3"><h3 className="display-serif font-bold text-[#49382f] whitespace-nowrap">{title}</h3></div>{children}</section>}
function NarrativeSection({title,value,fallback,editing,onChange}){return <Section title={title}>{editing?<textarea value={value||''} onChange={e=>onChange(e.target.value)} className="w-full min-h-24 p-3 bg-[#fffdf5] border border-[#d2c2a5] rounded-xl outline-none focus:border-[#8c5a50]"/>:<p className={`text-sm whitespace-pre-wrap leading-relaxed ${value?'text-[#4e4037]':'text-[#9a8d81] italic'}`}>{value||fallback}</p>}</Section>}
function SkillEditor({hero,toggleHeroSkill}){return <details className="mt-4"><summary className="cursor-pointer text-xs font-bold text-[#7b2d2d]">Edit skill list</summary><div className="mt-3 grid grid-cols-2 sm:grid-cols-3 gap-2">{Object.values(SKILLS).flat().map(skill=><label key={skill} className="flex items-center gap-2 text-xs text-[#5c4a3d]"><input type="checkbox" checked={hero.skills.includes(skill)} onChange={()=>toggleHeroSkill(hero.id,skill)} className="accent-[#7b2d2d]"/>{skill}</label>)}</div></details>}
