import React, { useRef, useState } from 'react';
import { Award, BookOpen, Compass, Home, Map, Save, Upload, Users } from 'lucide-react';
import AchievementsScreen from './screens/AchievementsScreen';
import HeroesScreen from './screens/HeroesScreen';
import PartyScreen from './screens/PartyScreen';
import SessionScreen from './screens/SessionScreen';
import VillageScreen from './screens/VillageScreen';
import { useCampaign } from './state/useCampaign';
import { useCampaignActions } from './state/useCampaignActions';

export default function App(){
 const [activeTab,setActiveTab]=useState('home'); const [editingHero,setEditingHero]=useState(null); const importInputRef=useRef(null); const campaign=useCampaign(); const actions=useCampaignActions(campaign); const {party,setParty,heroes,adventure,village,achievements,replaceCampaign,exportCampaign}=campaign;
 const exportSave=()=>{const blob=new Blob([JSON.stringify(exportCampaign(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`dragonholt-save-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);};
 const importSave=event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{replaceCampaign(JSON.parse(reader.result));setEditingHero(null);}catch{alert('That file does not look like a Dragonholt Companion save.');}event.target.value='';};reader.readAsText(file);};
 const createHero=details=>{const hero=actions.createHero(details);setEditingHero(hero.id);return hero;}; const deleteHero=id=>{actions.deleteHero(id);setEditingHero(null);}; const heroScreenProps={heroes,editingHero,setEditingHero,createHero,updateHero:actions.updateHero,deleteHero,toggleHeroSkill:actions.toggleHeroSkill,toggleDisabledSkill:actions.toggleDisabledSkill};
 const tabs=[{id:'home',icon:Home,desktop:'Journal',mobile:'Journal'},{id:'party',icon:BookOpen,desktop:'Story & Party',mobile:'Story'},{id:'heroes',icon:Users,desktop:'Heroes',mobile:'Heroes'},{id:'village',icon:Map,desktop:'Dragonholt',mobile:'Village'},{id:'achievements',icon:Award,desktop:'Trophies',mobile:'Awards'}];
 return <div className="journal-shell min-h-screen text-[#35271f] pb-24 md:pb-10">
  <header className="relative overflow-hidden border-b border-[#5e3029] bg-[#2d211c] text-[#f8f0dc] shadow-[0_8px_24px_rgba(48,30,20,.18)]"><div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_top_left,#b88747,transparent_42%)]"/><div className="relative max-w-5xl mx-auto px-4 py-4 sm:py-5 flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0"><div className="w-11 h-11 rounded-full border border-[#b58a54] flex items-center justify-center bg-[#3a2922] shadow-inner shrink-0"><Compass size={24} className="text-[#d4ad72]"/></div><div className="min-w-0"><div className="ink-label text-[9px] text-[#cbb58e]">A field journal for</div><h1 className="display-serif text-xl sm:text-2xl font-bold truncate">Legacy of Dragonholt</h1></div></div><div className="flex items-center gap-1.5"><button onClick={exportSave} title="Backup" className="p-2.5 sm:px-3 rounded-lg border border-[#5e493b] bg-[#3b2b24] text-[#ead9ba] hover:bg-[#49352b] flex items-center gap-2"><Save size={16}/><span className="hidden sm:inline text-xs font-bold">Backup</span></button><button onClick={()=>importInputRef.current?.click()} title="Restore" className="p-2.5 sm:px-3 rounded-lg border border-[#7c3a36] bg-[#6f2929] text-white hover:bg-[#812f2f] flex items-center gap-2"><Upload size={16}/><span className="hidden sm:inline text-xs font-bold">Restore</span></button><input ref={importInputRef} type="file" accept="application/json,.json" onChange={importSave} className="hidden"/></div></div></header>
  <main className="relative max-w-5xl mx-auto px-3 sm:px-5 py-5 sm:py-7"><nav className="hidden md:flex justify-center gap-1 mb-7 p-1.5 rounded-xl border border-[#bdaa88] bg-[#cec1a5]/75 shadow-inner">{tabs.map(tab=><button key={tab.id} onClick={()=>setActiveTab(tab.id)} className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-bold transition ${activeTab===tab.id?'bg-[#fff9e9] text-[#762b2b] shadow border border-[#c7b590]':'text-[#625044] hover:bg-[#e9dfc8]'}`}><tab.icon size={17}/>{tab.desktop}</button>)}</nav>
  <div>{activeTab==='home'&&<SessionScreen party={party} heroes={heroes} adventure={adventure} village={village} onAdvanceTime={actions.advanceTime} onOpenParty={()=>setActiveTab('party')} onOpenHeroes={()=>setActiveTab('heroes')} onOpenVillage={()=>setActiveTab('village')} onUpdateAdventure={actions.updateAdventure} onStartAdventure={actions.startAdventure} onCompleteAdventure={actions.completeAdventure}/>} {activeTab==='party'&&<PartyScreen party={party} setParty={setParty} onToggleStoryPoint={actions.toggleStoryPoint}/>} {activeTab==='heroes'&&<HeroesScreen {...heroScreenProps}/>} {activeTab==='village'&&<VillageScreen village={village} heroes={heroes} advanceTime={actions.advanceTime} nextDay={actions.nextDay} updateProgress={actions.updateProgress} claimHeroismMilestone={actions.claimHeroismMilestone} learnTrainingSkill={actions.learnTrainingSkill}/>} {activeTab==='achievements'&&<AchievementsScreen achievements={achievements} toggleAchievement={actions.toggleAchievement}/>}</div></main>
  <nav className="md:hidden fixed bottom-0 left-0 right-0 z-50 border-t border-[#604238] bg-[#2d211c]/[.97] text-[#cbbca5] shadow-[0_-8px_25px_rgba(43,29,22,.2)] flex justify-around px-1 pt-1.5 pb-safe">{tabs.map(tab=><button key={tab.id} onClick={()=>setActiveTab(tab.id)} className={`relative flex flex-1 flex-col items-center py-2 rounded-lg transition ${activeTab===tab.id?'text-[#f5dfb9]':''}`}><tab.icon size={20} strokeWidth={activeTab===tab.id?2.4:1.8}/><span className="ink-label text-[8px] mt-1 tracking-[.08em]">{tab.mobile}</span>{activeTab===tab.id&&<span className="absolute -top-1.5 w-7 h-[2px] bg-[#b33b3b] rounded-full"/>}</button>)}</nav>
 </div>;
}
